# **This is my first notebook**

In [1]:
print("Hello World")

Hello World

In [2]:
import pandas as pd

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [18]:
df=pd.read_csv('/content/drive/My Drive/data_science_workshop/test_data.csv',index_col='sample_name')
df.head()

             column0 column1 column2  column3  column4
sample_name
sample1      control     yes    0.25     0.10     0.00
sample2         case     yes     0.9     0.25     0.75
sample3      control     yes    0.43     0.23     0.02
sample4         case      no    c084     0.34     0.90

In [8]:
df.head()

   column0 column1 column2  column3  column4 sample_name
0  control     yes    0.25     0.10     0.00     sample1
1     case     yes     0.9     0.25     0.75     sample2
2  control     yes    0.43     0.23     0.02     sample3
3     case      no    c084     0.34     0.90     sample4

In [12]:
df['column2']

sample_name
sample1    0.25
sample2     0.9
sample3    0.43
sample4    c084
Name: column2, dtype: object

In [16]:
df1=df[['column2','column4']]
df1.head()

            column2  column4
sample_name
sample1        0.25     0.00
sample2         0.9     0.75
sample3        0.43     0.02
sample4        c084     0.90

In [20]:
df['column34']=df['column3']+df['column4']
df.head()

             column0 column1 column2  column3  column4  column34
sample_name
sample1      control     yes    0.25     0.10     0.00      0.10
sample2         case     yes     0.9     0.25     0.75      1.00
sample3      control     yes    0.43     0.23     0.02      0.25
sample4         case      no    c084     0.34     0.90      1.24

In [26]:
df['column01']=df['column0']+ "_" + df['column1']
df.head()

             column0 column1 column2  column3  column4  column34     column01
sample_name
sample1      control     yes    0.25     0.10     0.00      0.10  control_yes
sample2         case     yes     0.9     0.25     0.75      1.00     case_yes
sample3      control     yes    0.43     0.23     0.02      0.25  control_yes
sample4         case      no    c084     0.34     0.90      1.24      case_no

In [31]:
df.loc[df['column0']=='control','new_column0']=10
df.loc[df['column0']=='case','new_column0']=9
df.head()

             column0 column1 column2  ...  column34     column01  new_column0
sample_name                           ...
sample1      control     yes    0.25  ...      0.10  control_yes         10.0
sample2         case     yes     0.9  ...      1.00     case_yes          9.0
sample3      control     yes    0.43  ...      0.25  control_yes         10.0
sample4         case      no    c084  ...      1.24      case_no          9.0

[4 rows x 8 columns]

In [32]:
df.loc[df['column0']=='control']

             column0 column1 column2  ...  column34     column01  new_column0
sample_name                           ...
sample1      control     yes    0.25  ...      0.10  control_yes         10.0
sample3      control     yes    0.43  ...      0.25  control_yes         10.0

[2 rows x 8 columns]

In [38]:
df.loc[df['column2']>0.5]

TypeError: ignored

In [35]:
df.loc[df['column3']>0.15]

             column0 column1 column2  ...  column34     column01  new_column0
sample_name                           ...
sample2         case     yes     0.9  ...      1.00     case_yes          9.0
sample3      control     yes    0.43  ...      0.25  control_yes         10.0
sample4         case      no    c084  ...      1.24      case_no          9.0

[3 rows x 8 columns]

In [36]:
df.dtypes

column0         object
column1         object
column2         object
column3        float64
column4        float64
column34       float64
column01        object
new_column0    float64
dtype: object

In [44]:
pd.to_numeric(df['column2'],errors='coerce')

sample_name
sample1    0.25
sample2    0.90
sample3    0.43
sample4     NaN
Name: column2, dtype: float64

In [47]:
df['column2']=pd.to_numeric(df['column2'],errors='coerce')
df.head()

             column0 column1  column2  ...  column34     column01  new_column0
sample_name                            ...
sample1      control     yes     0.25  ...      0.10  control_yes         10.0
sample2         case     yes     0.90  ...      1.00     case_yes          9.0
sample3      control     yes     0.43  ...      0.25  control_yes         10.0
sample4         case      no      NaN  ...      1.24      case_no          9.0

[4 rows x 8 columns]

In [50]:
df['column2']=pd.to_numeric(df['column2'],errors='coerce')
df=df.dropna(subset=['column2'])
df.head()

             column0 column1  column2  ...  column34     column01  new_column0
sample_name                            ...
sample1      control     yes     0.25  ...      0.10  control_yes         10.0
sample2         case     yes     0.90  ...      1.00     case_yes          9.0
sample3      control     yes     0.43  ...      0.25  control_yes         10.0

[3 rows x 8 columns]

In [54]:
df=df.dropna(how='all')
df.head()

             column0 column1 column2  column3  column4
sample_name
sample1      control     yes    0.25     0.10     0.00
sample2         case     yes     0.9     0.25     0.75
sample3      control     yes    0.43     0.23     0.02
sample4         case      no    c084     0.34     0.90

In [12]:
df['column2']=pd.to_numeric(df['column2'],errors='coerce')
df.head()

             column0 column1  column2  column3  column4
sample_name
sample1      control     yes     0.25     0.10     0.00
sample2         case     yes     0.90     0.25     0.75
sample3      control     yes     0.43     0.23     0.02
sample4         case      no      NaN     0.34     0.90

In [58]:
df=df.dropna(how='any')
df.head()

             column0 column1  column2  column3  column4
sample_name
sample1      control     yes     0.25     0.10     0.00
sample2         case     yes     0.90     0.25     0.75
sample3      control     yes     0.43     0.23     0.02

In [64]:
df.fillna(0)

             column0 column1  column2  column3  column4
sample_name
sample1      control     yes     0.25     0.10     0.00
sample2         case     yes     0.90     0.25     0.75
sample3      control     yes     0.43     0.23     0.02
sample4         case      no     0.00     0.34     0.90

In [5]:
df2=pd.read_csv('/content/drive/My Drive/data_science_workshop/test_data2.csv',index_col='sample_name')
df2.head()

             age
sample_name
sample1       25
sample4       33
sample3       55

In [19]:
df_full=df.merge(df2,on='sample_name')
df_full.head()

             column0 column1 column2  column3  column4  age
sample_name
sample1      control     yes    0.25     0.10     0.00   25
sample3      control     yes    0.43     0.23     0.02   55
sample4         case      no    c084     0.34     0.90   33

In [20]:
df_full=df.merge(df2,on='sample_name',how='inner')
df_full.head()

             column0 column1 column2  column3  column4  age
sample_name
sample1      control     yes    0.25     0.10     0.00   25
sample3      control     yes    0.43     0.23     0.02   55
sample4         case      no    c084     0.34     0.90   33

In [21]:
df_full=df.merge(df2,on='sample_name',how='outer')
df_full.head()

             column0 column1 column2  column3  column4   age
sample_name
sample1      control     yes    0.25     0.10     0.00  25.0
sample2         case     yes     0.9     0.25     0.75   NaN
sample3      control     yes    0.43     0.23     0.02  55.0
sample4         case      no    c084     0.34     0.90  33.0

In [25]:
df3=pd.read_csv('/content/drive/My Drive/data_science_workshop/test_data3.csv',index_col='sample_name')
df3.head()

             age column1
sample_name
sample1       25     yes
sample4       33      no
sample3       55     yes

In [27]:
df_full=df.merge(df3,on=['sample_name','column1'])
df_full.head()

             column0 column1 column2  column3  column4  age
sample_name
sample1      control     yes    0.25     0.10     0.00   25
sample3      control     yes    0.43     0.23     0.02   55
sample4         case      no    c084     0.34     0.90   33

In [28]:
df.head()

             column0 column1 column2  column3  column4
sample_name
sample1      control     yes    0.25     0.10     0.00
sample2         case     yes     0.9     0.25     0.75
sample3      control     yes    0.43     0.23     0.02
sample4         case      no    c084     0.34     0.90

In [29]:
df=df.reset_index()
df.head()

  sample_name  column0 column1 column2  column3  column4
0     sample1  control     yes    0.25     0.10     0.00
1     sample2     case     yes     0.9     0.25     0.75
2     sample3  control     yes    0.43     0.23     0.02
3     sample4     case      no    c084     0.34     0.90

In [32]:
df_full.loc[df_full['age']>25,'age_cat']='gt10'
df_full.loc[df_full['age']<=25,'age_cat']='lt10'

df_full

             column0 column1 column2  column3  column4  age age_cat
sample_name
sample1      control     yes    0.25     0.10     0.00   25    lt10
sample3      control     yes    0.43     0.23     0.02   55    gt10
sample4         case      no    c084     0.34     0.90   33    gt10

In [33]:
new_group=df_full.groupby('column0').mean()
new_group.head()

         column3  column4  age
column0
case       0.340     0.90   33
control    0.165     0.01   40

In [34]:
new_group=df_full.groupby(['column0','age_cat']).mean()
new_group.head()

                 column3  column4  age
column0 age_cat
case    gt10        0.34     0.90   33
control gt10        0.23     0.02   55
        lt10        0.10     0.00   25

In [36]:
df_full.to_csv('/content/drive/My Drive/data_science_workshop/test_data_full.csv')

In [38]:
new_group.to_csv('/content/drive/My Drive/data_science_workshop/test_data_group.csv')